[package]
name = "ipgeolocate"
version = "0.2.2"
authors = ["DefunctLizard <grantshandy@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
description = "Get IP address geolocation information freely."
repository = "https://github.com/DefunctLizard/locator/"
documentation = "https://docs.rs/locator"
keywords = ["geolocation", "ip", "locator", "geolocator"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1.5.1"
serde_json = "1.0.59"
